server:
  port: 8761

spring:
    application:
        name: eureka-server
eureka:
    client:
        fetch-registry: false # Do not fetch registry from other Eureka servers(for standalone mode)
        service-url:
            defaultZone: http://localhost:8761/eureka/ # URL for the Eureka server to register with itself